Update NNCF version to 1.5
ovextra/mmdetection pull request #80
Opened 2020-11-18 18:50 UTC by aleksei-kashapov

2020-11-18 18:52 UTC, aleksei-kashapov commented
run tests

2020-11-19 10:34 UTC, LeonidBeynenson commented
2 @aleksei-kashapov :    
Aleksei, please, 
* uncomment `prepare_for_export` in `tools/export.py`
* grep `1.4.1` in documentation and replace it with `1.5.0`

2020-11-19 10:35 UTC, LeonidBeynenson commented on requirements/nncf_compression.txt
> +nncf==1.5
`1.5.0`

2020-11-19 10:35 UTC, LeonidBeynenson commented on mmdet/integration/nncf/compression.py
> +        if isinstance(img, list):
Please, add `assert len(img) == 1`

Also, please, add explanation messages for all `assert`-s in this function

2020-11-19 10:54 UTC, aleksei-kashapov commented
run tests

2020-11-20 11:51 UTC, LeonidBeynenson commented
2 @Ilya-Krylov, @aleksei-kashapov :   
I'm generally accept this change, but I ask Aleksei to check full pipeline on one more model (e.g. `retinanet`).

Aleksei, please, write when you check it, and IMHO this PR will be ready for merge.

2020-11-20 13:24 UTC, aleksei-kashapov commented
I done the experiment that Leonid asked. `retinanet `model works fine for all possible scenario (train, test, export, test_exported)

2020-11-20 21:35 UTC, LeonidBeynenson commented
2 @Ilya-Krylov:    
Ilya, I think this PR is fine. Please, merge it if you agree with it.

2020-11-23 10:48 UTC, Ilya-Krylov commented
run tests

2020-11-23 10:52 UTC, druzhkov-paul requested changes
@aleksei-kashapov Please add NNCF version to `mmdet/utils/collect_env.py` and checkpoints meta.

2020-11-23 18:29 UTC, aleksei-kashapov commented
> @aleksei-kashapov Please add NNCF version to `mmdet/utils/collect_env.py` and checkpoints meta.

@druzhkov-paul `mmdet/utils/collect_env.py` - Done
could you specify where I should add changes to add NNCF version to checkpoints meta?

2020-11-24 08:51 UTC, druzhkov-paul commented
Ok, I see that it's already in there. Thanks.

2020-11-24 08:51 UTC, druzhkov-paul commented
run tests

2020-11-24 08:51 UTC, druzhkov-paul approved these changes

2020-12-01 12:33 UTC, Ilya-Krylov commented
This branch is out-of-date with the base branch

2020-12-06 12:05 UTC, aleksei-kashapov commented
run tests

2020-12-07 05:25 UTC, merged